-- =============================================================================
-- AchievementsConfig.lua - PIT Rank & Achievement System
-- License: AGPL-3.0 - https://www.gnu.org/licenses/agpl-3.0.html
-- =============================================================================
return {
    min_speed_for_progress = 30,
    actions = {
        marker_capture       = { base=50,  role="mixed"    },
        close_marker_capture = { base=250, role="mixed"    },
        bust                 = { base=25,  role="police"   },
        escape               = { base=50,  role="civilian" },
        zigzag_pressure      = { base=15,  role="civilian" },
        combo_escape         = { base=50,  role="civilian" },
        cop_marker_chase     = { base=75,  role="police"   },
        wanted_marker_chase  = { base=75,  role="civilian" },
    },
    ranks = {
        { threshold=0,       prefix="[I]",     reward=0       },
        { threshold=300,     prefix="[II]",    reward=3000    },
        { threshold=800,     prefix="[III]",   reward=5000    },
        { threshold=2000,    prefix="[IV]",    reward=6500    },
        { threshold=5000,    prefix="[V]",     reward=8000    },
        { threshold=10000,   prefix="[VI]",    reward=12000   },
        { threshold=18000,   prefix="[VII]",   reward=16000   },
        { threshold=30000,   prefix="[VIII]",  reward=22000   },
        { threshold=45000,   prefix="[IX]",    reward=28000   },
        { threshold=65000,   prefix="[X]",     reward=35000   },
        { threshold=90000,   prefix="[XI]",    reward=45000   },
        { threshold=120000,  prefix="[XII]",   reward=55000   },
        { threshold=155000,  prefix="[XIII]",  reward=70000   },
        { threshold=195000,  prefix="[XIV]",   reward=85000   },
        { threshold=240000,  prefix="[XV]",    reward=100000  },
        { threshold=290000,  prefix="[XVI]",   reward=120000  },
        { threshold=345000,  prefix="[XVII]",  reward=140000  },
        { threshold=400000,  prefix="[XVIII]", reward=160000  },
        { threshold=455000,  prefix="[XIX]",   reward=180000  },
        { threshold=500000,  prefix="[XX]",    reward=250000  },
    },
    milestones = {
        -- A. Total markers
        { id="mc_first", stat="total_markers", threshold=1,    base_points=25,    role="mixed",    name_key="ms_mc_first"                     },
        { id="mc_10",    stat="total_markers", threshold=10,   base_points=500,   role="mixed",    name_key="ms_mc_10",   requires="mc_first" },
        { id="mc_50",    stat="total_markers", threshold=50,   base_points=750,   role="mixed",    name_key="ms_mc_50",   requires="mc_10"    },
        { id="mc_100",   stat="total_markers", threshold=100,  base_points=2000,  role="mixed",    name_key="ms_mc_100",  requires="mc_50"    },
        { id="mc_250",   stat="total_markers", threshold=250,  base_points=4000,  role="mixed",    name_key="ms_mc_250",  requires="mc_100"   },
        { id="mc_500",   stat="total_markers", threshold=500,  base_points=8000,  role="mixed",    name_key="ms_mc_500",  requires="mc_250"   },
        { id="mc_1000",  stat="total_markers", threshold=1000, base_points=15000, role="mixed",    name_key="ms_mc_1000", requires="mc_500"   },
        -- B. Close markers
        { id="cmc_first", stat="close_markers", threshold=1,   base_points=50,    role="mixed",    name_key="ms_cmc_first"                      },
        { id="cmc_10",    stat="close_markers", threshold=10,  base_points=1000,  role="mixed",    name_key="ms_cmc_10",   requires="cmc_first" },
        { id="cmc_50",    stat="close_markers", threshold=50,  base_points=2500,  role="mixed",    name_key="ms_cmc_50",   requires="cmc_10"    },
        { id="cmc_100",   stat="close_markers", threshold=100, base_points=5000,  role="mixed",    name_key="ms_cmc_100",  requires="cmc_50"    },
        { id="cmc_250",   stat="close_markers", threshold=250, base_points=10000, role="mixed",    name_key="ms_cmc_250",  requires="cmc_100"   },
        { id="cmc_500",   stat="close_markers", threshold=500, base_points=20000, role="mixed",    name_key="ms_cmc_500",  requires="cmc_250"   },
        -- C. Cop markers during chase
        { id="cop_mc_5",   stat="cop_marker_chase", threshold=5,   base_points=500,   role="police", name_key="ms_cop_mc_5"                          },
        { id="cop_mc_15",  stat="cop_marker_chase", threshold=15,  base_points=1500,  role="police", name_key="ms_cop_mc_15",  requires="cop_mc_5"   },
        { id="cop_mc_30",  stat="cop_marker_chase", threshold=30,  base_points=3000,  role="police", name_key="ms_cop_mc_30",  requires="cop_mc_15"  },
        { id="cop_mc_60",  stat="cop_marker_chase", threshold=60,  base_points=6000,  role="police", name_key="ms_cop_mc_60",  requires="cop_mc_30"  },
        { id="cop_mc_100", stat="cop_marker_chase", threshold=100, base_points=12000, role="police", name_key="ms_cop_mc_100", requires="cop_mc_60"  },
        -- D. Wanted markers during escape
        { id="want_mc_5",   stat="wanted_marker_chase", threshold=5,   base_points=500,   role="civilian", name_key="ms_want_mc_5"                           },
        { id="want_mc_15",  stat="wanted_marker_chase", threshold=15,  base_points=1500,  role="civilian", name_key="ms_want_mc_15",  requires="want_mc_5"   },
        { id="want_mc_30",  stat="wanted_marker_chase", threshold=30,  base_points=3000,  role="civilian", name_key="ms_want_mc_30",  requires="want_mc_15"  },
        { id="want_mc_60",  stat="wanted_marker_chase", threshold=60,  base_points=6000,  role="civilian", name_key="ms_want_mc_60",  requires="want_mc_30"  },
        { id="want_mc_100", stat="wanted_marker_chase", threshold=100, base_points=12000, role="civilian", name_key="ms_want_mc_100", requires="want_mc_60"  },
        -- E. Cop cumulative chase time (seconds)
        { id="cop_ct_2m",  stat="cop_chase_time", threshold=120,   base_points=100,   role="police", name_key="ms_cop_ct_2m"                          },
        { id="cop_ct_10m", stat="cop_chase_time", threshold=600,   base_points=250,   role="police", name_key="ms_cop_ct_10m",  requires="cop_ct_2m"  },
        { id="cop_ct_30m", stat="cop_chase_time", threshold=1800,  base_points=600,   role="police", name_key="ms_cop_ct_30m",  requires="cop_ct_10m" },
        { id="cop_ct_1h",  stat="cop_chase_time", threshold=3600,  base_points=1200,  role="police", name_key="ms_cop_ct_1h",   requires="cop_ct_30m" },
        { id="cop_ct_2h",  stat="cop_chase_time", threshold=7200,  base_points=2000,  role="police", name_key="ms_cop_ct_2h",   requires="cop_ct_1h"  },
        { id="cop_ct_5h",  stat="cop_chase_time", threshold=18000, base_points=4000,  role="police", name_key="ms_cop_ct_5h",   requires="cop_ct_2h"  },
        { id="cop_ct_10h", stat="cop_chase_time", threshold=36000, base_points=8000,  role="police", name_key="ms_cop_ct_10h",  requires="cop_ct_5h"  },
        { id="cop_ct_25h", stat="cop_chase_time", threshold=90000, base_points=18000, role="police", name_key="ms_cop_ct_25h",  requires="cop_ct_10h" },
        -- F. Wanted cumulative chase time (seconds)
        { id="want_ct_2m",  stat="wanted_chase_time", threshold=120,   base_points=100,   role="civilian", name_key="ms_want_ct_2m"                           },
        { id="want_ct_10m", stat="wanted_chase_time", threshold=600,   base_points=250,   role="civilian", name_key="ms_want_ct_10m",  requires="want_ct_2m"  },
        { id="want_ct_30m", stat="wanted_chase_time", threshold=1800,  base_points=600,   role="civilian", name_key="ms_want_ct_30m",  requires="want_ct_10m" },
        { id="want_ct_1h",  stat="wanted_chase_time", threshold=3600,  base_points=1000,  role="civilian", name_key="ms_want_ct_1h",   requires="want_ct_30m" },
        { id="want_ct_2h",  stat="wanted_chase_time", threshold=7200,  base_points=1800,  role="civilian", name_key="ms_want_ct_2h",   requires="want_ct_1h"  },
        { id="want_ct_5h",  stat="wanted_chase_time", threshold=18000, base_points=3500,  role="civilian", name_key="ms_want_ct_5h",   requires="want_ct_2h"  },
        { id="want_ct_10h", stat="wanted_chase_time", threshold=36000, base_points=7000,  role="civilian", name_key="ms_want_ct_10h",  requires="want_ct_5h"  },
        { id="want_ct_25h", stat="wanted_chase_time", threshold=90000, base_points=15000, role="civilian", name_key="ms_want_ct_25h",  requires="want_ct_10h" },
        -- I. Busts
        { id="bust_1",   stat="busts", threshold=1,   base_points=100,   role="police", name_key="ms_bust_1"                        },
        { id="bust_5",   stat="busts", threshold=5,   base_points=300,   role="police", name_key="ms_bust_5",   requires="bust_1"   },
        { id="bust_10",  stat="busts", threshold=10,  base_points=600,   role="police", name_key="ms_bust_10",  requires="bust_5"   },
        { id="bust_25",  stat="busts", threshold=25,  base_points=1500,  role="police", name_key="ms_bust_25",  requires="bust_10"  },
        { id="bust_50",  stat="busts", threshold=50,  base_points=3000,  role="police", name_key="ms_bust_50",  requires="bust_25"  },
        { id="bust_100", stat="busts", threshold=100, base_points=6000,  role="police", name_key="ms_bust_100", requires="bust_50"  },
        { id="bust_250", stat="busts", threshold=250, base_points=15000, role="police", name_key="ms_bust_250", requires="bust_100" },
        -- J. Escapes
        { id="esc_1",   stat="escapes", threshold=1,   base_points=100,   role="civilian", name_key="ms_esc_1"                       },
        { id="esc_5",   stat="escapes", threshold=5,   base_points=300,   role="civilian", name_key="ms_esc_5",   requires="esc_1"   },
        { id="esc_10",  stat="escapes", threshold=10,  base_points=600,   role="civilian", name_key="ms_esc_10",  requires="esc_5"   },
        { id="esc_25",  stat="escapes", threshold=25,  base_points=1500,  role="civilian", name_key="ms_esc_25",  requires="esc_10"  },
        { id="esc_50",  stat="escapes", threshold=50,  base_points=3000,  role="civilian", name_key="ms_esc_50",  requires="esc_25"  },
        { id="esc_100", stat="escapes", threshold=100, base_points=6000,  role="civilian", name_key="ms_esc_100", requires="esc_50"  },
        { id="esc_250", stat="escapes", threshold=250, base_points=15000, role="civilian", name_key="ms_esc_250", requires="esc_100" },
        -- K. Zigzag
        { id="zz_3",   stat="zigzag_count", threshold=3,   base_points=150,  role="civilian", name_key="ms_zz_3"                      },
        { id="zz_10",  stat="zigzag_count", threshold=10,  base_points=400,  role="civilian", name_key="ms_zz_10",  requires="zz_3"   },
        { id="zz_25",  stat="zigzag_count", threshold=25,  base_points=1000, role="civilian", name_key="ms_zz_25",  requires="zz_10"  },
        { id="zz_50",  stat="zigzag_count", threshold=50,  base_points=2500, role="civilian", name_key="ms_zz_50",  requires="zz_25"  },
        { id="zz_100", stat="zigzag_count", threshold=100, base_points=6000, role="civilian", name_key="ms_zz_100", requires="zz_50"  },
        -- L. Combo escape
        { id="combo_1",  stat="combo_count", threshold=1,  base_points=200,  role="civilian", name_key="ms_combo_1"                       },
        { id="combo_5",  stat="combo_count", threshold=5,  base_points=700,  role="civilian", name_key="ms_combo_5",  requires="combo_1"  },
        { id="combo_15", stat="combo_count", threshold=15, base_points=1800, role="civilian", name_key="ms_combo_15", requires="combo_5"  },
        { id="combo_30", stat="combo_count", threshold=30, base_points=4000, role="civilian", name_key="ms_combo_30", requires="combo_15" },
        { id="combo_50", stat="combo_count", threshold=50, base_points=8000, role="civilian", name_key="ms_combo_50", requires="combo_30" },
        -- M. Single session time (session=true)
        { id="sess_30m", stat="session_seconds", threshold=1800,  base_points=100,  role="none", session=true, name_key="ms_sess_30m"                      },
        { id="sess_1h",  stat="session_seconds", threshold=3600,  base_points=300,  role="none", session=true, name_key="ms_sess_1h",  requires="sess_30m" },
        { id="sess_2h",  stat="session_seconds", threshold=7200,  base_points=600,  role="none", session=true, name_key="ms_sess_2h",  requires="sess_1h"  },
        { id="sess_3h",  stat="session_seconds", threshold=10800, base_points=1000, role="none", session=true, name_key="ms_sess_3h",  requires="sess_2h"  },
        { id="sess_5h",  stat="session_seconds", threshold=18000, base_points=2500, role="none", session=true, name_key="ms_sess_5h",  requires="sess_3h"  },
        -- N. Total playtime (seconds)
        { id="play_5h",   stat="total_playtime", threshold=18000,  base_points=300,   role="none", name_key="ms_play_5h"                         },
        { id="play_10h",  stat="total_playtime", threshold=36000,  base_points=700,   role="none", name_key="ms_play_10h",  requires="play_5h"   },
        { id="play_25h",  stat="total_playtime", threshold=90000,  base_points=1500,  role="none", name_key="ms_play_25h",  requires="play_10h"  },
        { id="play_50h",  stat="total_playtime", threshold=180000, base_points=3000,  role="none", name_key="ms_play_50h",  requires="play_25h"  },
        { id="play_100h", stat="total_playtime", threshold=360000, base_points=7000,  role="none", name_key="ms_play_100h", requires="play_50h"  },
        { id="play_250h", stat="total_playtime", threshold=900000, base_points=18000, role="none", name_key="ms_play_250h", requires="play_100h" },
        -- O. Login streaks
        { id="str_2",  stat="streak_days", threshold=2,  base_points=1000,  role="none", name_key="ms_str_2"                     },
        { id="str_3",  stat="streak_days", threshold=3,  base_points=2000,  role="none", name_key="ms_str_3",  requires="str_2"  },
        { id="str_5",  stat="streak_days", threshold=5,  base_points=5000,  role="none", name_key="ms_str_5",  requires="str_3"  },
        { id="str_7",  stat="streak_days", threshold=7,  base_points=8000,  role="none", name_key="ms_str_7",  requires="str_5"  },
        { id="str_14", stat="streak_days", threshold=14, base_points=20000, role="none", name_key="ms_str_14", requires="str_7"  },
        -- P. Spike strips used
        { id="spike_1",   stat="spike_used", threshold=1,   base_points=50,   role="police", name_key="ms_spike_1"                         },
        { id="spike_10",  stat="spike_used", threshold=10,  base_points=200,  role="police", name_key="ms_spike_10",  requires="spike_1"   },
        { id="spike_25",  stat="spike_used", threshold=25,  base_points=500,  role="police", name_key="ms_spike_25",  requires="spike_10"  },
        { id="spike_50",  stat="spike_used", threshold=50,  base_points=1200, role="police", name_key="ms_spike_50",  requires="spike_25"  },
        { id="spike_100", stat="spike_used", threshold=100, base_points=3000, role="police", name_key="ms_spike_100", requires="spike_50"  },
        -- Q. Bananas used
        { id="banana_1",   stat="banana_used", threshold=1,   base_points=50,   role="police", name_key="ms_banana_1"                          },
        { id="banana_10",  stat="banana_used", threshold=10,  base_points=200,  role="police", name_key="ms_banana_10",  requires="banana_1"   },
        { id="banana_25",  stat="banana_used", threshold=25,  base_points=500,  role="police", name_key="ms_banana_25",  requires="banana_10"  },
        { id="banana_50",  stat="banana_used", threshold=50,  base_points=1200, role="police", name_key="ms_banana_50",  requires="banana_25"  },
        { id="banana_100", stat="banana_used", threshold=100, base_points=3000, role="police", name_key="ms_banana_100", requires="banana_50"  },
        -- R. Cannon used
        { id="cannon_1",   stat="cannon_used", threshold=1,   base_points=50,   role="police", name_key="ms_cannon_1"                          },
        { id="cannon_10",  stat="cannon_used", threshold=10,  base_points=200,  role="police", name_key="ms_cannon_10",  requires="cannon_1"   },
        { id="cannon_25",  stat="cannon_used", threshold=25,  base_points=500,  role="police", name_key="ms_cannon_25",  requires="cannon_10"  },
        { id="cannon_50",  stat="cannon_used", threshold=50,  base_points=1200, role="police", name_key="ms_cannon_50",  requires="cannon_25"  },
        { id="cannon_100", stat="cannon_used", threshold=100, base_points=3000, role="police", name_key="ms_cannon_100", requires="cannon_50"  },
        -- S. Spike hits
        { id="spike_hit_1",  stat="spike_hits", threshold=1,  base_points=100,  role="police", name_key="ms_spike_hit_1"                           },
        { id="spike_hit_10", stat="spike_hits", threshold=10, base_points=400,  role="police", name_key="ms_spike_hit_10", requires="spike_hit_1"  },
        { id="spike_hit_25", stat="spike_hits", threshold=25, base_points=1000, role="police", name_key="ms_spike_hit_25", requires="spike_hit_10" },
        { id="spike_hit_50", stat="spike_hits", threshold=50, base_points=2500, role="police", name_key="ms_spike_hit_50", requires="spike_hit_25" },
        -- T. Banana hits
        { id="banana_hit_1",  stat="banana_hits", threshold=1,  base_points=100,  role="police", name_key="ms_banana_hit_1"                            },
        { id="banana_hit_10", stat="banana_hits", threshold=10, base_points=400,  role="police", name_key="ms_banana_hit_10", requires="banana_hit_1"  },
        { id="banana_hit_25", stat="banana_hits", threshold=25, base_points=1000, role="police", name_key="ms_banana_hit_25", requires="banana_hit_10" },
        { id="banana_hit_50", stat="banana_hits", threshold=50, base_points=2500, role="police", name_key="ms_banana_hit_50", requires="banana_hit_25" },
        -- U. Cannon hits
        { id="cannon_hit_1",  stat="cannon_hits", threshold=1,  base_points=100,  role="police", name_key="ms_cannon_hit_1"                            },
        { id="cannon_hit_10", stat="cannon_hits", threshold=10, base_points=400,  role="police", name_key="ms_cannon_hit_10", requires="cannon_hit_1"  },
        { id="cannon_hit_25", stat="cannon_hits", threshold=25, base_points=1000, role="police", name_key="ms_cannon_hit_25", requires="cannon_hit_10" },
        { id="cannon_hit_50", stat="cannon_hits", threshold=50, base_points=2500, role="police", name_key="ms_cannon_hit_50", requires="cannon_hit_25" },
        -- V. Session perf - cop (session=true)
        { id="s_bust_3",    stat="session_busts",       threshold=3,  base_points=200,  role="police",   session=true, name_key="ms_s_bust_3"                            },
        { id="s_bust_5",    stat="session_busts",       threshold=5,  base_points=400,  role="police",   session=true, name_key="ms_s_bust_5",    requires="s_bust_3"    },
        { id="s_bust_10",   stat="session_busts",       threshold=10, base_points=1000, role="police",   session=true, name_key="ms_s_bust_10",   requires="s_bust_5"    },
        { id="s_cop_mc_10", stat="session_cop_markers", threshold=10, base_points=200,  role="police",   session=true, name_key="ms_s_cop_mc_10"                         },
        { id="s_cop_mc_25", stat="session_cop_markers", threshold=25, base_points=500,  role="police",   session=true, name_key="ms_s_cop_mc_25", requires="s_cop_mc_10" },
        { id="s_cop_mc_50", stat="session_cop_markers", threshold=50, base_points=1500, role="police",   session=true, name_key="ms_s_cop_mc_50", requires="s_cop_mc_25" },
        -- W. Session perf - wanted (session=true)
        { id="s_esc_3",  stat="session_escapes", threshold=3,  base_points=200,  role="civilian", session=true, name_key="ms_s_esc_3"                      },
        { id="s_esc_5",  stat="session_escapes", threshold=5,  base_points=400,  role="civilian", session=true, name_key="ms_s_esc_5",  requires="s_esc_3" },
        { id="s_esc_10", stat="session_escapes", threshold=10, base_points=1000, role="civilian", session=true, name_key="ms_s_esc_10", requires="s_esc_5" },
        { id="s_zz_5",   stat="session_zigzags", threshold=5,  base_points=200,  role="civilian", session=true, name_key="ms_s_zz_5"                       },
        { id="s_zz_10",  stat="session_zigzags", threshold=10, base_points=500,  role="civilian", session=true, name_key="ms_s_zz_10",  requires="s_zz_5"  },
        -- AA. Session points (session=true)
        { id="s_pts_1k",  stat="session_points", threshold=1000,  base_points=200,  role="none", session=true, name_key="ms_s_pts_1k"                       },
        { id="s_pts_5k",  stat="session_points", threshold=5000,  base_points=600,  role="none", session=true, name_key="ms_s_pts_5k",  requires="s_pts_1k" },
        { id="s_pts_15k", stat="session_points", threshold=15000, base_points=1500, role="none", session=true, name_key="ms_s_pts_15k", requires="s_pts_5k" },
    },
}
