return {
    marker_spawned_color = "^b",

    keys = {
        invalid_target                = "^e",
        no_money                      = "^e",
        cool_player_message           = "^e",
        added_money_per_minute        = "^e",
        welcome_server                = "^e",
        welcome_police                = "^e",
        welcome_civilian              = "^e",
        speed_start_wanted            = "^e",
        zigzag_start_wanted           = "^e",
        wanted_extended               = "^e",
        busted_global_message         = "^e",
        repair_too_fast               = "^e",
        civilian_repair_success       = "^e",
        police_repair_wanted_nearby   = "^e",
        police_repair_success         = "^e",
        civilian_repair_police_nearby = "^e",
        teleport_cooldown             = "^e",
        teleport_on_edit              = "^e",
        teleport_on_reset             = "^e",
        teleport_on_change            = "^e",
        marker_captured               = "^e",
        transfer_limit_reached        = "^e",
        transfer_moderator_limit      = "^e",
        wanted_fail_global            = "^e",
        wanted_escape_global          = "^e",
        airpolluter_success_broadcast = "^e",
        airpolluter_fail_broadcast    = "^e",
        purchase_success              = "^e",

        zigzag_end_reward             = "^a",
        speeding_end_reward           = "^a",
        evaded_both_bonus             = "^a",
        police_bust_bonus             = "^a",
        marker_reward_success         = "^a",
        airpolluter_success           = "^a",

        wanted_fail_message           = "^c",
        wanted_global_speeding        = "^c",
        wanted_global_zigzag          = "^c",
        airpolluter_fail_message      = "^c",
        series_banned                 = "^c",
    }
}
