-- =============================================================================
-- PIT Economy System - Message Colors
-- Version: 5.0
-- License: AGPL-3.0 - https://www.gnu.org/licenses/agpl-3.0.html
-- =============================================================================

return {
    marker_spawned_color              = "^b",
    keys = {
        invalid_target                = "^#FF4545",
        no_money                      = "^#FF4545",
        pay_sent                      = "^#2ECC71",
        pay_received                  = "^#2ECC71",
        lang_not_found                = "^#FF4545",
        language_changed              = "^#2ECC71",
        added_money_per_minute        = "^#FFD700",
        welcome_server                = "^#FFD700",
        welcome_police                = "^#1E90FF",
        welcome_civilian              = "^#FFD700",
        speed_start_wanted            = "^#FF4545^@#FFFFFF",
        zigzag_start_wanted           = "^#FF4545^@#FFFFFF",
        zigzag_end_reward             = "^#FFFFFF^@#2ECC71",
        wanted_extended               = "^#FF4545^@#FFFFFF",
        wanted_fail_message           = "❌^#FFFFFF^@#FF4545",
        speeding_end_reward           = "^#2ECC71^@#FFFFFF",
        evaded_both_bonus             = "^#2ECC71^@#FFFFFF",
        busted_global_message         = "^#FF4545^@#131313",
        police_bust_bonus             = "^#FFFFFF^@#2ECC71",
        repair_too_fast               = "^#FF4545",
        civilian_not_wanted           = "^#FF4545",
        civilian_no_repairs           = "^#FF4545",
        civilian_no_repairs_left      = "^#FF4545",
        civilian_repair_success       = "^#2ECC71",
        police_repair_wanted_nearby   = "^#FF4545",
        police_no_repairs_left        = "^#FF4545",
        police_repair_success         = "^#2ECC71",
        civilian_repair_police_nearby = "^#FF4545",
        teleport_cooldown             = "^#FF4545",
        marker_reward_success         = "^#FFFFFF^@#2ECC71",
        marker_reward_limit           = "^#2ECC71",
        airpolluter_start_broadcast   = "^#9370DB^@#131313",
        airpolluter_success           = "^#FFFFFF^@#2ECC71",
        airpolluter_fail_message      = "❌^#FFFFFF^@#FF4545",
        airpolluter_success_broadcast = "^#9370DB",
        airpolluter_fail_broadcast    = "^#FF4545^@#131313",
        powerup_bonus_spike           = "^#FFFFFF^@#FFD700",
        powerup_bonus_banana          = "^#FFFFFF^@#FFD700",
        powerup_not_available         = "^#FF4545",
        powerup_no_spikes             = "^#FF4545",
        powerup_speed_limit           = "^#FF4545",
        powerup_no_bananas            = "^#FF4545",
        powerup_bonus_cannon          = "^#FFD700",
        powerup_no_cannon             = "^#FF4545",
        blocker_mission_success       = "^#FFFFFF^@#2ECC71",
        blocker_mission_failed        = "^#FFFFFF^@#FF4545",
        blocker_money_share           = "^#FFFFFF^@#2ECC71",
        blocker_already_active        = "^#FF4545",
        blocker_started_broadcast     = "^#FFD700",
        blocker_success_broadcast     = "^#FFD700^@#FFFFFF",
        blocker_fail_broadcast        = "^#FF4545^@#131313",
    }
}