-- =============================================================================
-- PoliceSkins.lua
-- List of vehicle skin/paint identifiers that grant the police role.
-- Add any custom police skin IDs here to extend role detection.
-- License: AGPL-3.0 — https://www.gnu.org/licenses/agpl-3.0.html
-- =============================================================================

return {
    "autobello_skin_carabinieri",
    "midtruck_skin_carabinieri",
    "bastion_skin_policeb",
    "legran_skin_police",
    "nine_skin_police",
    "burnside_skin_police",
    "vivace_skin_polizia",
    "vivace_skin_gendarmerie",
    "bolide_skin_polizia",
    "scintilla_skin_police",
    "etk800_skin_police",
    "etk800_skin_polizei",
    "etk800_skin_polizia",
    "etkc_skin_polizei",
    "bluebuck_skin_police",
    "bluebuck_skin_police2",
    "pickup_skin_parkranger",
    "fullsize_skin_bcpd",
    "fullsize_skin_police",
    "fullsize_skin_policeinterceptor",
    "sunburst2_body_sedan",
    "van_skin_glass_tint",
    "van_skin_police_alt",
    "md_series_reversewarn",
    "roamer_skin_sheriff",
    "roamer_skin_bcpd",
    "sunburst2_skin_gendarmerie",
    "sunburst2_skin_police",
    "sunburst2_skin_policeBelasco",
    "sunburst2_skin_policeinterceptor",
    "sunburst2_skin_polizia",
    "sunburst2_skin_polizia_alt",
    "bx_skin_police",
    "bx_skin_police_firwood",
    "covet_skin_police",
    "hopper_skin_sheriff",
    "hopper_skin_parkranger",
    "midsize_skin_statetrooper",
    "lansdale_skin_security",
    "pessima_skin_police",
    "wendover_skin_interceptor",
--    "lansdale_skin_police",
--    "midsize_skin_police",
--    "etki_skin_police",
--    "moonhawk_skin_police",
--    "fullsize_limo_skin_police",
}
